### ISSUE TITLE
tweak installer crash

### ISSUE THREAD

**Issue by MarcoIanne** [josephwalden13/tweak-installer#28]
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\Users\marco\Desktop\Tweak instaler\files\Library\MobileSubstrate\DynamicLibraries' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Unjailbreaker.Program.emptyDir(String path)
   at Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
It probably means something else is using the file. Try closing all folders and trying again
