### ISSUE TITLE
Tweak Installer stopped working

### ISSUE THREAD

**Issue by NeurosisRevisableUnkempt** [josephwalden13/tweak-installer#3]
Unhandled Exception: System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
Which OS are you running it on? and 32bit or 64bit?

**Comment by NeurosisRevisableUnkempt** [comment]
32bit

**Comment by josephwalden13** [comment]
My entire program was made for 32 bit, but the 7zip stuff was 64 only. I've added a 32bit build here :)
https://github.com/josephwalden13/tweak-installer/releases/tag/beta6%2C1

**Comment by NeurosisRevisableUnkempt** [comment]
Thank you very much :) will test it out now

**Comment by NeurosisRevisableUnkempt** [comment]
It works! :)
