### ISSUE TITLE
Tweak Installer Crash

### ISSUE THREAD

**Issue by boygenious** [josephwalden13/tweak-installer#30]
WinSCP.SessionRemoteException: Network error: Connection to "192.168.1.16" timed out.
   at WinSCP.SessionLogReader.Read(LogReadFlags flags)
   at WinSCP.ElementLogReader.Read(LogReadFlags flags)
   at WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   at WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.Session.Open(SessionOptions sessionOptions)
   at Unjailbreaker.Program.Main(String[] args)
Tweak Installer v1.2.2

**Comment by josephwalden13** [comment]
This is an error with your connection, not my tool. Make sure ssh is running on your phone
