### ISSUE TITLE
Installer crashes when trying to install tweak

### ISSUE THREAD

**Issue by csamples22** [josephwalden13/tweak-installer#44]
The installer seems to run perfectly fine then I get this error code:
Unhandled Exception: System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at Unjailbreaker.Program.<>c__DisplayClass18_0.<Main>b__1(String i)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
Delete the settings file and try again
