### ISSUE TITLE
conection to "xxx.xxx.x.xx" time out

### ISSUE THREAD

**Issue by Rauljbb** [josephwalden13/tweak-installer#52]
WinSCP.SessionRemoteException: Network error: Connection to "192.168.0.19" timed out.
   at WinSCP.SessionLogReader.Read(LogReadFlags flags)
   at WinSCP.ElementLogReader.Read(LogReadFlags flags)
   at WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   at WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.Session.Open(SessionOptions sessionOptions)
   at Unjailbreaker.Program.Main(String[] args)

**Comment by josephwalden13** [comment]
Make sure you’re jailbroken, that your ip, password and port are correct. And if so try rebooting and rejailbreaking as this isn’t a problem with my tool, it’s a problem with the ssh connection

**Comment by Rauljbb** [comment]
thanks, but i already do all that, and the tool still can't connect to my phone.
i know this isn't a problem whit your tool but i really appreciate if you could help me

**Comment by josephwalden13** [comment]
Try creating a usb tunnel (http://iphonedevwiki.net/index.php/SSH_Over_USB#SSH_over_USB_using_the_iFunBox_GUI_.28Windows_only.29) and setting the IP address to 127.0.0.1 and see if it works.

Also, which jailbreak are you using?

**Comment by Rauljbb** [comment]
I´m using Electra b10, but the usb tunnel works, so I guess I´ve must do that evrey time I'm run the program, thank you very much. ( I don´t have a very great english, and i really can't express, but muchas gracias! :D )
