### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shotguntuck** [josephwalden13/tweak-installer#60]
WinSCP.SessionRemoteException: Network error: Connection to "198.169.1.100" timed out.
   at WinSCP.SessionLogReader.Read(LogReadFlags flags)
   at WinSCP.ElementLogReader.Read(LogReadFlags flags)
   at WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   at WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.Session.Open(SessionOptions sessionOptions)
   at Tweak_Installer.Main.getSession(String ip, String user, String password, Int32 port)

**Comment by josephwalden13** [comment]
Check ssh login settings
