### ISSUE TITLE
error and not connecting to device

### ISSUE THREAD

**Issue by RaymondChen299** [josephwalden13/tweak-installer#71]
WinSCP.SessionRemoteException: Network error: Connection to "192.168.2.21" timed out.
   在 WinSCP.SessionLogReader.Read(LogReadFlags flags)
   在 WinSCP.ElementLogReader.Read(LogReadFlags flags)
   在 WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   在 WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   在 WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   在 WinSCP.Session.Open(SessionOptions sessionOptions)
   在 Tweak_Installer.Main.getSession(String ip, String user, String password, Int32 port)

**Comment by Blaqdymun** [comment]
WinSCP.SessionRemoteException: Network error: Connection to "192.168.0.11" timed out.
   at WinSCP.SessionLogReader.Read(LogReadFlags flags)
   at WinSCP.ElementLogReader.Read(LogReadFlags flags)
   at WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   at WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.Session.Open(SessionOptions sessionOptions)
   at Tweak_Installer.Main.getSession(String ip, String user, String password, Int32 port)

**Comment by josephwalden13** [comment]
Problem with ssh, not my tool

**Comment by RaymondChen299** [comment]
Ok, thank you though.

在 2018年2月28日，13:17，josephwalden13 <notifications@github.com<mailto:notifications@github.com>> 写道：


Problem with ssh, not my tool
