### ISSUE TITLE
Error when installing SCOthman for Snapchat 

### ISSUE THREAD

**Issue by iOSCem** [josephwalden13/tweak-installer#72]
This is the error

WinSCP.SessionRemoteException: Network error: Connection to "192.168.2.13" timed out.
   at WinSCP.SessionLogReader.Read(LogReadFlags flags)
   at WinSCP.ElementLogReader.Read(LogReadFlags flags)
   at WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   at WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.Session.Open(SessionOptions sessionOptions)
   at Tweak_Installer.Main.getSession(String ip, String user, String password, Int32 port)

**Comment by josephwalden13** [comment]
This is due to connection to ssh failing and isn’t a problem with my tool. Try rebooting and trying again. Although now that Cydia is released, it’s really easy to install it using that anyway
