### ISSUE TITLE
error2 /no such file

### ISSUE THREAD

**Issue by dvxaznxvb** [josephwalden13/tweak-installer#75]
************** Exception Text **************
WinSCP.SessionRemoteException: Error creating folder '/bootstrap/Library/Themes'.
No such file or directory.
Error code: 2
Error message from server: No such file
   at WinSCP.SessionLogReader.Read(LogReadFlags flags)
   at WinSCP.ElementLogReader.Read(LogReadFlags flags)
   at WinSCP.SessionElementLogReader.Read(LogReadFlags flags)
   at WinSCP.ElementLogReader.Read(LogReadFlags flags)
   at WinSCP.CustomLogReader.TryWaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.CustomLogReader.WaitForNonEmptyElement(String localName, LogReadFlags flags)
   at WinSCP.Session.CreateDirectory(String path)
   at Tweak_Installer.Main.getJailbreakSpecificOptions(Session session)
   at Tweak_Installer.Main.install_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

checked for ssh opening and confirmed with another program

**Comment by josephwalden13** [comment]
Electra 1.0 completely changes the way it works. I will eventually update this to support Electra 1.2, but with Cydia it’s probably quite useless :D

**Comment by josephwalden13** [comment]
Actually it’s a simple fix so I’ll  do it later
